import os
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

import torch
from torch.utils.data import Dataset, DataLoader

from utils.tools import StandardScaler
from utils.timefeatures import time_features

import warnings

warnings.filterwarnings('ignore')


class Dataset_MTS(Dataset):
    def __init__(self, root_path, data_path='ETTh1.csv', flag='train', size=None, features='M',
                 data_split=[0.7, 0.1, 0.2], scale=True, scale_statistic=None, target='OT', timeenc=0, freq='h', cycle=None):
        # size [seq_len, label_len, pred_len]
        # info
        self.in_len = size[0]
        self.label_len = size[1]
        self.pred_len = size[2]
        # init
        assert flag in ['train', 'test', 'val']
        type_map = {'train': 0, 'val': 1, 'test': 2}
        self.set_type = type_map[flag]
        self.flag = flag

        self.scale = scale
        # self.inverse = inverse

        self.root_path = root_path
        self.data_path = data_path
        self.data_split = data_split
        self.scale_statistic = scale_statistic
        self.__read_data__()

    def __read_data__(self):
        df_raw = pd.read_csv(os.path.join(self.root_path, self.data_path))
        if (self.data_split[0] < 1):
            train_num = int(len(df_raw) * self.data_split[0])
            test_num = int(len(df_raw) * self.data_split[2])
            val_num = len(df_raw) - train_num - test_num
        else:
            train_num = self.data_split[0]
            val_num = self.data_split[1]
            test_num = self.data_split[2]
        border1s = [0, train_num - self.in_len, train_num + val_num - self.in_len]
        border2s = [train_num, train_num + val_num, train_num + val_num + test_num]

        border1 = border1s[self.set_type]
        border2 = border2s[self.set_type]

        cols_data = df_raw.columns[1:]
        df_data = df_raw[cols_data]

        # assume, first col = timestamp, last col = label
        cols_data = df_raw.columns[1:-1]  # all feature columns
        col_label = df_raw.columns[-1]  # the label column

        df_data = df_raw[cols_data]
        df_label = df_raw[[col_label]]

        if self.scale:
            if self.scale_statistic is None:
                self.scaler = StandardScaler()
                train_data = df_data[border1s[0]:border2s[0]]
                self.scaler.fit(train_data.values)
            else:
                self.scaler = StandardScaler(mean=self.scale_statistic['mean'], std=self.scale_statistic['std'])
            data = self.scaler.transform(df_data.values)
        else:
            data = df_data.values
        data_label = df_label.values  # raw labels, no scaling

        self.data_x = data[border1:border2]
        self.data_y = data[border1:border2]
        self.data_label = data_label[border1:border2]

    def __getitem__(self, index):
        s_begin = index
        s_end = s_begin + self.in_len
        r_begin = s_end - self.label_len
        r_end = r_begin + self.label_len + self.pred_len

        seq_x = self.data_x[s_begin:s_end]
        seq_y = self.data_y[r_begin:r_end]
        label_y = self.data_label[s_begin:s_end]  # corresponding labels

        seq_x_mark = 6.5
        seq_y_mark = 5.3
        cycle_index = 6
        return seq_x, seq_y, seq_x_mark, seq_y_mark, cycle_index, label_y

    def __len__(self):
        return len(self.data_x) - self.in_len - self.pred_len + 1

    def inverse_transform(self, data):
        return self.scaler.inverse_transform(data)



class Dataset_MTS_NPY(Dataset):
    """
    NPY loader for pre-windowed files generated by data_processing.py.
    Expected files under {root_path}/{data_path}:
        train_x.npy, train_y.npy, val_x.npy, val_y.npy, test_x.npy, test_y.npy
    """

    def __init__(self, root_path, data_path, flag='train', size=None, features='M',
                 target='OT', timeenc=0, freq='h', cycle=None, npy_mode='std',
                 merge_to_series=False, scale_statistic=None):
        assert flag in ['train', 'val', 'test']
        assert size is not None and len(size) == 3, "size must be [seq_len, label_len, pred_len]"

        self.seq_len = size[0]
        self.label_len = size[1]
        self.pred_len = size[2]
        self.flag = flag
        self.root_path = root_path
        self.data_path = data_path
        self.features = features
        self.target = target
        self.timeenc = timeenc
        self.freq = freq
        self.cycle = cycle
        self.npy_mode = npy_mode
        self.merge_to_series = merge_to_series
        self.scale_statistic = scale_statistic

        self.data_x = None
        self.data_y_full = None
        self.data_x_sel = None
        self.data_y_target = None
        self.series_x = None
        self.series_y = None
        self.series_label = None
        self.series_cycle = None

        self.__read_data__()

    def __read_data__(self):
        base_dir = os.path.join(self.root_path, self.data_path)
        x_path = os.path.join(base_dir, f"{self.flag}_x.npy")
        y_path = os.path.join(base_dir, f"{self.flag}_y.npy")

        if not os.path.isfile(x_path):
            raise FileNotFoundError(f"Missing file: {x_path}")
        if not os.path.isfile(y_path):
            raise FileNotFoundError(f"Missing file: {y_path}")

        self.data_x = np.load(x_path).astype(np.float32)      # (N, seq_len, Cx)
        self.data_y_full = np.load(y_path).astype(np.float32) # (N, out_len, Cy)

        if self.data_x.ndim != 3 or self.data_y_full.ndim != 3:
            raise ValueError("NPY shapes must be 3D: x=(N,T,Cx), y=(N,H,Cy)")
        if self.data_x.shape[1] != self.seq_len:
            raise ValueError(f"seq_len mismatch: x has {self.data_x.shape[1]}, expected {self.seq_len}")
        if self.data_y_full.shape[1] < self.pred_len:
            raise ValueError(f"pred_len mismatch: y has {self.data_y_full.shape[1]}, expected >= {self.pred_len}")
        if self.npy_mode not in ['all', 'ori', 'std']:
            raise ValueError("npy_mode must be one of ['all', 'ori', 'std']")

        # y channel 4 = raw ground-truth in original pipeline; fallback to channel 0 for manual labels.
        y_target_col = 4 if self.data_y_full.shape[2] > 4 else 0
        self.data_y_target = self.data_y_full[:, :, [y_target_col]]

        # x channel mapping from original get_data: ori->6, std->5, all->all.
        if self.npy_mode == 'ori':
            x_col = 6 if self.data_x.shape[2] > 6 else 0
            self.data_x_sel = self.data_x[:, :, [x_col]]
        elif self.npy_mode == 'std':
            x_col = 5 if self.data_x.shape[2] > 5 else 0
            self.data_x_sel = self.data_x[:, :, [x_col]]
        else:
            self.data_x_sel = self.data_x

        if self.merge_to_series:
            self.series_x = self.data_x_sel.reshape(-1, self.data_x_sel.shape[-1])
            self.series_y = self.data_y_target.reshape(-1, 1)
            self.series_label = self.series_y.copy()
            if self.cycle is not None and self.cycle > 0:
                self.series_cycle = (np.arange(len(self.series_x)) % self.cycle)
            else:
                self.series_cycle = np.arange(len(self.series_x))

    def __getitem__(self, index):
        if self.merge_to_series:
            s_begin = index
            s_end = s_begin + self.seq_len
            r_begin = s_end - self.label_len
            r_end = r_begin + self.label_len + self.pred_len

            seq_x = self.series_x[s_begin:s_end]
            seq_y = self.series_y[r_begin:r_end]
            label_y = self.series_label[s_begin:s_end]
            seq_x_mark = 6.5
            seq_y_mark = 5.3
            cycle_index = torch.tensor(self.series_cycle[s_end - 1])
            return seq_x, seq_y, seq_x_mark, seq_y_mark, cycle_index, label_y

        seq_x = self.data_x_sel[index]             # (seq_len, Cx_sel)
        y_target = self.data_y_target[index]       # (out_len, 1)

        # Build decoder-aligned target: [label_len history + pred_len future]
        history = seq_x[-self.label_len:, :1] if self.label_len > 0 else np.zeros((0, 1), dtype=np.float32)
        future = y_target[:self.pred_len, :]
        seq_y = np.concatenate([history, future], axis=0)

        label_y = seq_x[:, :1]
        seq_x_mark = 6.5
        seq_y_mark = 5.3
        if self.cycle is not None and self.cycle > 0:
            cycle_index = torch.tensor(index % self.cycle)
        else:
            cycle_index = torch.tensor(index)
        return seq_x, seq_y, seq_x_mark, seq_y_mark, cycle_index, label_y

    def __len__(self):
        if self.merge_to_series:
            return len(self.series_x) - self.seq_len - self.pred_len + 1
        return self.data_x_sel.shape[0]

    def inverse_transform(self, data):
        return data


class Dataset_ETT_hour(Dataset):
    def __init__(self, root_path, flag='train', size=None,
                 features='S', data_path='ETTh1.csv',
                 target='OT', scale=True, timeenc=0, freq='h', cycle=None):
        # size [seq_len, label_len, pred_len]
        # info
        if size == None:
            self.seq_len = 24 * 4 * 4
            self.label_len = 24 * 4
            self.pred_len = 24 * 4
        else:
            self.seq_len = size[0]
            self.label_len = size[1]
            self.pred_len = size[2]
        # init
        assert flag in ['train', 'test', 'val']
        type_map = {'train': 0, 'val': 1, 'test': 2}
        self.set_type = type_map[flag]

        self.features = features
        self.target = target
        self.scale = scale
        self.timeenc = timeenc
        self.freq = freq
        self.cycle = cycle

        self.root_path = root_path
        self.data_path = data_path
        self.__read_data__()

    def __read_data__(self):
        self.scaler = StandardScaler()
        df_raw = pd.read_csv(os.path.join(self.root_path,
                                          self.data_path))

        border1s = [0, 12 * 30 * 24 - self.seq_len, 12 * 30 * 24 + 4 * 30 * 24 - self.seq_len]
        border2s = [12 * 30 * 24, 12 * 30 * 24 + 4 * 30 * 24, 12 * 30 * 24 + 8 * 30 * 24]
        border1 = border1s[self.set_type]
        border2 = border2s[self.set_type]

        # split features + label
        cols_feat = df_raw.columns[1:-1]  # everything except date and label
        col_label = df_raw.columns[-1]  # last column is label
        df_feat = df_raw[cols_feat]
        df_label = df_raw[[col_label]]
        data_label = df_label.values  # no scaling

        if self.features == 'M' or self.features == 'MS':
            # cols_data = df_raw.columns[1:]
            # df_data = df_raw[cols_data]
            df_data = df_feat
        elif self.features == 'S':
            df_data = df_raw[[self.target]]

        if self.scale:
            train_data = df_data[border1s[0]:border2s[0]]
            self.scaler.fit(train_data.values)
            data = self.scaler.transform(df_data.values)
        else:
            data = df_data.values

        df_stamp = df_raw[['date']][border1:border2]
        df_stamp['date'] = pd.to_datetime(df_stamp.date)
        if self.timeenc == 0:
            df_stamp['month'] = df_stamp.date.apply(lambda row: row.month, 1)
            df_stamp['day'] = df_stamp.date.apply(lambda row: row.day, 1)
            df_stamp['weekday'] = df_stamp.date.apply(lambda row: row.weekday(), 1)
            df_stamp['hour'] = df_stamp.date.apply(lambda row: row.hour, 1)
            data_stamp = df_stamp.drop(['date'], 1).values
        elif self.timeenc == 1:
            data_stamp = time_features(pd.to_datetime(df_stamp['date'].values), freq=self.freq)
            data_stamp = data_stamp.transpose(1, 0)

        self.data_x = data[border1:border2]
        self.data_y = data[border1:border2]
        self.data_stamp = data_stamp

        # NEW: keep labels aligned with current split borders
        self.data_label = data_label[border1:border2]

        # add cycle
        self.cycle_index = (np.arange(len(data)) % self.cycle)[border1:border2]

    def __getitem__(self, index):
        s_begin = index
        s_end = s_begin + self.seq_len
        r_begin = s_end - self.label_len
        r_end = r_begin + self.label_len + self.pred_len

        seq_x = self.data_x[s_begin:s_end]
        seq_y = self.data_y[r_begin:r_end]
        seq_x_mark = self.data_stamp[s_begin:s_end]
        seq_y_mark = self.data_stamp[r_begin:r_end]

        cycle_index = torch.tensor(self.cycle_index[s_end])

        # NEW: label_y aligned with input window
        label_y = self.data_label[s_begin:s_end]
        return seq_x, seq_y, seq_x_mark, seq_y_mark, cycle_index, label_y

    def __len__(self):
        return len(self.data_x) - self.seq_len - self.pred_len + 1

    def inverse_transform(self, data):
        return self.scaler.inverse_transform(data)

class Dataset_ETT_minute(Dataset):
    def __init__(self, root_path, flag='train', size=None,
                 features='S', data_path='ETTm1.csv',
                 target='OT', scale=True, timeenc=0, freq='t', cycle=None):
        # size [seq_len, label_len, pred_len]
        # info
        if size == None:
            self.seq_len = 24 * 4 * 4
            self.label_len = 24 * 4
            self.pred_len = 24 * 4
        else:
            self.seq_len = size[0]
            self.label_len = size[1]
            self.pred_len = size[2]
        # init
        assert flag in ['train', 'test', 'val']
        type_map = {'train': 0, 'val': 1, 'test': 2}
        self.set_type = type_map[flag]

        self.features = features
        self.target = target
        self.scale = scale
        self.timeenc = timeenc
        self.freq = freq
        self.cycle = cycle

        self.root_path = root_path
        self.data_path = data_path
        self.__read_data__()

    def __read_data__(self):
        self.scaler = StandardScaler()
        df_raw = pd.read_csv(os.path.join(self.root_path,
                                          self.data_path))

        border1s = [0, 12 * 30 * 24 * 4 - self.seq_len, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4 - self.seq_len]
        border2s = [12 * 30 * 24 * 4, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4, 12 * 30 * 24 * 4 + 8 * 30 * 24 * 4]
        border1 = border1s[self.set_type]
        border2 = border2s[self.set_type]

        # split features + label
        cols_feat = df_raw.columns[1:-1]  # everything except date and label
        col_label = df_raw.columns[-1]  # last column is label
        df_feat = df_raw[cols_feat]
        df_label = df_raw[[col_label]]
        data_label = df_label.values  # no scaling

        if self.features == 'M' or self.features == 'MS':
            # cols_data = df_raw.columns[1:]
            # df_data = df_raw[cols_data]
            df_data = df_feat
        elif self.features == 'S':
            df_data = df_raw[[self.target]]



        if self.scale:
            train_data = df_data[border1s[0]:border2s[0]]
            self.scaler.fit(train_data.values)
            data = self.scaler.transform(df_data.values)
        else:
            data = df_data.values


        df_stamp = df_raw[['date']][border1:border2]
        df_stamp['date'] = pd.to_datetime(df_stamp.date)
        if self.timeenc == 0:
            df_stamp['month'] = df_stamp.date.apply(lambda row: row.month, 1)
            df_stamp['day'] = df_stamp.date.apply(lambda row: row.day, 1)
            df_stamp['weekday'] = df_stamp.date.apply(lambda row: row.weekday(), 1)
            df_stamp['hour'] = df_stamp.date.apply(lambda row: row.hour, 1)
            df_stamp['minute'] = df_stamp.date.apply(lambda row: row.minute, 1)
            df_stamp['minute'] = df_stamp.minute.map(lambda x: x // 15)
            data_stamp = df_stamp.drop(['date'], 1).values
        elif self.timeenc == 1:
            data_stamp = time_features(pd.to_datetime(df_stamp['date'].values), freq=self.freq)
            data_stamp = data_stamp.transpose(1, 0)

        self.data_x = data[border1:border2]
        self.data_y = data[border1:border2]
        self.data_stamp = data_stamp

        # NEW: keep labels aligned with current split borders
        self.data_label = data_label[border1:border2]

        # add cycle
        self.cycle_index = (np.arange(len(data)) % self.cycle)[border1:border2]

    def __getitem__(self, index):
        s_begin = index
        s_end = s_begin + self.seq_len
        r_begin = s_end - self.label_len
        r_end = r_begin + self.label_len + self.pred_len

        seq_x = self.data_x[s_begin:s_end]
        seq_y = self.data_y[r_begin:r_end]
        seq_x_mark = self.data_stamp[s_begin:s_end]
        seq_y_mark = self.data_stamp[r_begin:r_end]

        cycle_index = torch.tensor(self.cycle_index[s_end])
        # NEW: label_y aligned with input window
        label_y = self.data_label[s_begin:s_end]

        return seq_x, seq_y, seq_x_mark, seq_y_mark, cycle_index, label_y

    def __len__(self):
        return len(self.data_x) - self.seq_len - self.pred_len + 1

    def inverse_transform(self, data):
        return self.scaler.inverse_transform(data)
